apiVersion: v1
kind: Pod
metadata:
  name: "cli-test"
  labels:
    app: dev
    name: "cli-test"
spec:
  containers:
  - name: web
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
---
apiVersion: v1
kind: Service
metadata:
  name: "web-service"
spec:
  selector:
    app: dev
    name: "cli-test"
  ports:
  - name: http
    protocol: TCP
    port: 80

