# EROFORRAS DEFINICIO:
apiVersion: apps/v1
kind: Deployment  # eroforras fajtaja
metadata: # ezzel azonosithatova teszem az eroforrast, igy kesobb hivatkozhatok ra.
  name: webserver-deployment
  labels:      # ezen cimkekkel tudok majd hivatkozni erre az eroforrasra
    app: web-app-deployment
    type: tanfolyam-deployment

# POD DEFINICIO.
spec:             
  template:       #  teljes pod template definicio kovetkezik
    metadata:
      name: web-app-pod
      labels:
        app: web-app-label
        type: tanfolyam-label
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80

# DEPLOYMENT SPECIFIKUS DEFINICIO:
  replicas: 3       # hany darab pod fusson ebben a deployment-ben
  selector:         # meghatarozza hogy mely pod-okra illeszkedik ez a deployment
    matchLabels:    # cimke egyezes alapjan
      app: web-app-label # konkret pod cimkek.
      type: tanfolyam-label # konkret pod cimkek