apiVersion: v1
kind: Pod
metadata:
  name: web5
  labels:
    name: web5
spec:
  containers:
  - name: web5
    image: nginx:1.21
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
