apiVersion: v1
kind: Pod
metadata:
  name: web3
  labels:
    app: web
    name: web
    type: test
spec:
  - containers:
    name: web
    image: nginx:1.20
    livenessProbe:      # ellenorzi hogy az adott alkalmazas mukodokepes-s es ujrainditja a pod-ot
      httpGet:          # http get metodussal lekerjuk a /error oldalt
        path: /error
        port: 80
      initialDelaySeconds: 10 # az 1. ellenorzes elotti varakozas
      timeoutSeconds: 2
      periodSeconds: 5
      failereThreshold: 1
    startupProbe:
      httpGet:
        path: /test.html
        port: 80
      initialDelaySeconds: 300   # az az indulas utan ennyi varakozast kovetoen induljon a teszt