apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment4
  labels:
    app: dev
    type: front-end
    name: web
spec:
  replicas: 3
  selector:
    matchLabels:      
      app: dev
      type: front-end
      name: web
  template:
    metadata:
      labels:
        app: dev
        type: front-end
        name: web
    spec:
      containers:
      - name: apache
        image: smartopsacademy/apache:latest
        ports:
        - containerPort: 80
          name: http