apiVersion: v1
kind: Service
metadata:   # fontos a service-re valo hivatkozaskor a cimkezese
  name: php-svc
  labels:
    type: backend-service
    name: php-service
spec:
  type: ClusterIP # ez esetben belul lesz elerheto
  
  selector: # pod cimkek megadasa, amelyek fele kell iranyitani a forgalmat
    name: php-fpm
    app: app001
    type: backend 
  
  ports: 
  - port: 9000 # ezen a porton erheto el a service belul (ClasterIP)
    targetPort: 9000 # a service ezen eri el a pod-ot (a pod-ban megadottakal egyezoen)
    protocol: TCP
    nodePort: 30018 # konkretan is megadhatom a kulso portot, ha akarom

---

apiVersion: v1
kind: Pod
metadata:
  name: php-pod
  labels:
    name: php-fpm
    app: app001
    type: backend
spec:
  containers:
  - name: php-fpm
    image: php:8.0-fpm
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9000
