apiVersion: v1
kind: Service
metadata:   # fontos a service-re valo hivatkozaskor a cimkezese
  labels:
    type: front-end
    name: web
  name: web-service
spec:
  type: ClusterIP #ez esetben csak a clusteren belul lesz elerheto
  
  selector: # pod cimkek megadasa, amelyek fele kell iranyitani a forgalmat
    app: front-end
    name: web
  
  ports:
  - port: 80 # ezen a porton erheto el a service
    targetPort: 80 # a service ezen eri el a pod-ot (a pod-ban megadottakal egyezoen)
    protocol: TCP
    name: http # service port neve (opcionalis)
  
