apiVersion: v1
kind: Service
metadata:   # fontos a service-re valo hivatkozaskor a cimkezese
  name: web-service
  labels:
    type: frontend
    name: web
spec:
  type: NodePort # ez esetben kibul belul belul elerheto lesz
  
  selector: # pod cimkek megadasa, amelyek fele kell iranyitani a forgalmat
    app: web
    type: frontend
  
  ports:
  - port: 80 # ezen a porton erheto el a service belul (ClasterIP)
    targetPort: 80  # a service ezen eri el a pod-ot (a pod-ban megadottakal egyezoen)
    nodePort: 30015 # konkretan is megadhatom a kulso portot, ha akarom
  - port: 443 # ezen a porton erheto el a service belul (ClasterIP)
    targetPort: 443  # a service ezen eri el a pod-ot (a pod-ban megadottakal egyezoen)
    nodePort: 30016 # konkretan is megadhatom a kulso portot, ha akarom

  
