apiVersion: v1
kind: Service
metadata:   # fontos a service-re valo hivatkozaskor a cimkezese
  labels:
    name: php-service
    namespace: default
    
spec:
  type: ClusterIP #ez esetben csak a clusteren belul lesz elerheto
  
  selector: # pod cimkek megadasa, amelyek fele kell iranyitani a forgalmat
    app: php
    type: backend
  
  ports:
  - port: 9000 # ezen a porton erheto el a service
    targetPort: 9000 # a service ezen eri el a pod-ot (a pod-ban megadottakal egyezoen)

