apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: devopsakademia
    type: back-end
    name: php
spec:
  replicas: 3
  selector:
    matchLabels:      
      app: devopsakademia
      type: back-end
      name: php
  template:
    metadata:
      labels:
        app: devopsakademia
        type: back-end
        name: php
    spec:
      containers:
      - name: php
        image: smartopsacademy/php:alpine
        ports:
        - containerPort: 9000
          name: php
---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: devopsakademia
    type: back-end
    name: php
spec:
  type: ClusterIP
  ports:
  - name: php
    port: 9000
    targetPort: php
  selector:
    app: devopsakademia
    type: back-end
    name: php
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.204
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: devopsakademia
    type: front-end
    name: web
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  replicas: 3
  selector:
    matchLabels:      
      app: devopsakademia
      type: front-end
      name: web
  template:
    metadata:
      labels:
        app: devopsakademia
        type: front-end
        name: web
    spec:
      containers:
      - name: apache
        image: smartopsacademy/apache:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: FCGI
          value: "php:9000" # php nevu service 9000-es portjara kuldi a php kereseket

