apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: dev
  labels:
    app: devopsakademia
    type: back-end
    name: php
spec:
  replicas: 3
  selector:
    matchLabels:      
      app: devopsakademia
      type: back-end
      name: php
  template:
    metadata:
      labels:
        app: devopsakademia
        type: back-end
        name: php
    spec:
      containers:
      - name: php
        image: smartopsacademy/php:alpine
        ports:
        - containerPort: 9000
          name: php

---

apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: dev
  labels:
    app: devopsakademia
    type: back-end
    name: php
spec:
  type: ClusterIP
  ports:
  - name: php
    port: 9000
    targetPort: php
  selector:
    app: devopsakademia
    type: back-end
    name: php

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: dev
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  replicas: 3
  selector:
    matchLabels:      
      app: devopsakademia
      type: front-end
      name: web
  template:
    metadata:
      labels:
        app: devopsakademia
        type: front-end
        name: web
    spec:
      containers:
      - name: apache
        image: smartopsacademy/apache:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: FCGI
          value: php:9000

---

apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: dev
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30080
  selector:
    app: devopsakademia
    type: front-end
    name: web

---

apiVersion: v1
kind: Namespace
metadata:
  name:  dev

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-tesz-namespace
  namespace: dev
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 600Mi
    limits.cpu: '1'
    limits.memory: 600Mi
    pods: '3'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi




