apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  annotations: 
    reason1: "image updated"
    reason: "image  updated again"
  labels:
    type: front-end 
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 1
  selector:
    matchLabels:
      type: front-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  template:
    metadata:
      labels:
        type: front-end 
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
          - containerPort: 80