apiVersion: v1
kind: Namespace
metadata:
  name:  dev

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-tesz-namespace
  namespace: dev
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 300Mi
    limits.cpu: '1'
    limits.memory: 100Mi
    pods: '3'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: "web-pod"
 #namespace: prod # ebben a nevterben fog indulni a pod, de jobb parancssorbol megadni
  labels:
    app: "web-pod"
spec:
  containers:
  - name: nginx
    image: "nginx:1.22"
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    ports:
      - containerPort:  80
        name:  http
