apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  containers:
  - name: nginx
    image: nginx:1.22
    ports:
    - containerPort: 80
      name: http
