apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: devopsakademia
    type: front-end
    name: web
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30080
  selector:
    app: devopsakademia
    type: front-end
    name: web
